openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
  /contratos-generales:
    get:
      operationId: ContratoGeneralController_findAll
      summary: Obtener todos los contratos generales
      parameters: []
      responses:
        '200':
          description: Lista de contratos generales
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContratoGeneral'
      tags: &ref_0
        - contratos-generales
    post:
      operationId: ContratoGeneralController_create
      summary: Crear un nuevo contrato general
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearContratoGeneralDto'
      responses:
        '201':
          description: Contrato general creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContratoGeneral'
      tags: *ref_0
  /contratos-generales/{id}:
    get:
      operationId: ContratoGeneralController_findOne
      summary: Obtener un contrato general por ID
      parameters:
        - name: id
          required: true
          in: path
          description: ID del contrato general
          schema:
            type: number
      responses:
        '200':
          description: Contrato general encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContratoGeneral'
        '404':
          description: Contrato general no encontrado
      tags: *ref_0
    put:
      operationId: ContratoGeneralController_update
      summary: Actualizar un contrato general
      parameters:
        - name: id
          required: true
          in: path
          description: ID del contrato general a actualizar
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActualizarContratoGeneralDto'
      responses:
        '200':
          description: Contrato general actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContratoGeneral'
        '404':
          description: Contrato general no encontrado
      tags: *ref_0
    delete:
      operationId: ContratoGeneralController_remove
      summary: Eliminar un contrato general
      parameters:
        - name: id
          required: true
          in: path
          description: ID del contrato general a eliminar
          schema:
            type: number
      responses:
        '200':
          description: Contrato general eliminado
        '404':
          description: Contrato general no encontrado
      tags: *ref_0
  /documentos-contratos:
    post:
      operationId: DocumentoContratoController_create
      summary: Crear un nuevo documento contrato
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDocumentoContratoDto'
      responses:
        '201':
          description: El documento contrato ha sido creado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentoContrato'
        '400':
          description: Solicitud incorrecta.
      tags: &ref_1
        - documentos-contratos
    get:
      operationId: DocumentoContratoController_findAll
      summary: Obtener todos los documentos contratos
      parameters: []
      responses:
        '200':
          description: Devuelve todos los documentos contratos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentoContrato'
      tags: *ref_1
  /documentos-contratos/{id}:
    get:
      operationId: DocumentoContratoController_findOne
      summary: Obtener un documento contrato por id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Devuelve el documento contrato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentoContrato'
        '404':
          description: Documento contrato no encontrado.
      tags: *ref_1
    patch:
      operationId: DocumentoContratoController_update
      summary: Actualizar un documento contrato
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDocumentoContratoDto'
      responses:
        '200':
          description: El documento contrato ha sido actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentoContrato'
        '400':
          description: Solicitud incorrecta.
        '404':
          description: Documento contrato no encontrado.
      tags: *ref_1
    delete:
      operationId: DocumentoContratoController_remove
      summary: Eliminar un documento contrato
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: El documento contrato ha sido eliminado exitosamente.
        '404':
          description: Documento contrato no encontrado.
      tags: *ref_1
  /documentos-contratos/contrato/{contratoId}:
    get:
      operationId: DocumentoContratoController_findByContratoId
      summary: Obtener documentos contratos por id de contrato
      parameters:
        - name: contratoId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Devuelve los documentos contratos para el contrato especificado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentoContrato'
        '404':
          description: >-
            No se encontraron documentos contratos para el contrato
            especificado.
      tags: *ref_1
  /contratistas:
    post:
      operationId: ContratistaController_create
      summary: Crear un nuevo contratista
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContratistaDto'
      responses:
        '201':
          description: El contratista ha sido creado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contratista'
        '400':
          description: Solicitud incorrecta.
      tags: &ref_2
        - contratistas
    get:
      operationId: ContratistaController_findAll
      summary: Obtener todos los contratistas
      parameters: []
      responses:
        '200':
          description: Devuelve todos los contratistas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contratista'
      tags: *ref_2
  /contratistas/{id}:
    get:
      operationId: ContratistaController_findOne
      summary: Obtener un contratista por id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Devuelve el contratista.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contratista'
        '404':
          description: Contratista no encontrado.
      tags: *ref_2
    patch:
      operationId: ContratistaController_update
      summary: Actualizar un contratista
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContratistaDto'
      responses:
        '200':
          description: El contratista ha sido actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contratista'
        '400':
          description: Solicitud incorrecta.
        '404':
          description: Contratista no encontrado.
      tags: *ref_2
    delete:
      operationId: ContratistaController_remove
      summary: Eliminar un contratista
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: El contratista ha sido eliminado exitosamente.
        '404':
          description: Contratista no encontrado.
      tags: *ref_2
  /contratistas/by-contrato/{contratoId}:
    get:
      operationId: ContratistaController_findByContrato
      summary: Obtener contratista por id de contrato
      parameters:
        - name: contratoId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: Devuelve el contratista para el contrato especificado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contratista'
        '404':
          description: No se encontró contratista para el contrato especificado.
      tags: *ref_2
info:
  title: Gestion Contractual CRUD
  description: API para la gestión contractual
  version: '1.0'
  contact: {}
tags:
  - name: gestion-contractual
    description: ''
servers: []
components:
  schemas:
    ContratoGeneral:
      type: object
      properties: {}
    CrearContratoGeneralDto:
      type: object
      properties: {}
    ActualizarContratoGeneralDto:
      type: object
      properties: {}
    CreateDocumentoContratoDto:
      type: object
      properties: {}
    DocumentoContrato:
      type: object
      properties: {}
    UpdateDocumentoContratoDto:
      type: object
      properties: {}
    CreateContratistaDto:
      type: object
      properties: {}
    Contratista:
      type: object
      properties: {}
    UpdateContratistaDto:
      type: object
      properties: {}
